### ISSUE TITLE
Pytanie o spring security

### ISSUE THREAD

**Issue by PatrykZaniewski** [KonradMagiera/Food-Hero#45]
Panie Doktorze, wspominał Pan żeby w razie czego zwracać się do Pana z pytaniami i problemami w projekcie. Problem dotyczy uwierzytelniania w spring security.

W tabeli z danymi do logowania trzymam maila, hasło (w bcrypt), status konta (czy admin?) oraz status aktywności. Wygląda to tak:

> id bigserial NOT NULL,
    email text NOT NULL,
    password character(128) NOT NULL,
    is_admin boolean NOT NULL,
    is_active boolean NOT NULL,

Zaimplementowałem też klasę UserDetailsService, która odpowiedzialna jest za sprawdzanie czy użytkownik jest w bazie: 

> @Service
public class LoginDetailsService implements UserDetailsService {

    @Autowired
    private LoginService loginService;

    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        Login login = loginService.getLogin(email);
        if (login == null)
        {
            throw new UsernameNotFoundException(email);
        }
        Set<GrantedAuthority> grantedAuthorities = new HashSet< >();
        grantedAuthorities.add(new SimpleGrantedAuthority("ADMIN"));

        org.springframework.security.core.userdetails.User user = new org.springframework.security.core.userdetails.User(login.getEmail(), login.getPassword(),
                grantedAuthorities);

        System.out.println(user);
        return user;
    }
}

I na sam koniec plik konfiguracyjny springa:

>@Configuration
@EnableWebSecurity
public class SecurityConfigAuth extends WebSecurityConfigurerAdapter {

    @Autowired
    private UserDetailsService loginDetailsService;

    @Override
    protected void configure(AuthenticationManagerBuilder authenticationManagerBuilder) throws Exception {
        authenticationManagerBuilder
                .userDetailsService(loginDetailsService)
                .passwordEncoder(passwordEncoder());
    }

    @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .authorizeRequests()
                .antMatchers("/account/").hasAuthority("USER")
                .antMatchers("/").hasAuthority("ADMIN")
                .and()
                .formLogin(); //W celach testowych
        httpSecurity.sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
                .sessionFixation().migrateSession();
    }

    @Bean
    public BCryptPasswordEncoder passwordEncoder(){
        return new BCryptPasswordEncoder();
    }
}

Problemem jest to, że zawsze, ale to zawsze dostaję odmowę logowania. Myślałem, że to może coś z hasłami, a konkretnie z szyfrowaniem Bcrypta, więc zmieniłem Encoder na NoOp żeby trzymało hasło w plaintext, ale to też nie pomogło. 

Dodatkowo w klasie LoginDetailsService zrobiłem printa, który wypisuje mi użytkownika i jego dane też się zgadzają.

Przewertowałem chyba wszystkie te bardziej aktualne tutoriale z tym związane, ale tam działa, a tu nie działa  😭 .

**Comment by szmurlor** [comment]
Nie pomogę niestety nic konkretnie. Mogę tylko podpowiedzieć, jak ja starałbym się rozwiązać problem?

1. Ponieważ działa z tutorialami, to bym takiego tutoriala sobie sklonował - gołego.
2. Potem bym małymi krokami - pojedynczo dodawał do tego tutoriala rzeczy, które moim zdaniem potencjalnie mogą przeszkadzać, a są skonfigurowane w waszym projekcie. I sprawdziłbym wtedy kiedy to przestaje działać.
3. Koniecznie trzeba założyć debugging oraz w debuggerze w IntellijIDEI wyizolować dokładnie miejsce, gdzie następuje przerwanie łańcucha - i zaczyna się negatywna odpowiedź.

Przykro mi, że nie pomogę, ale tego typu problemu to minimum 3-4 godziny siedzenia z mojego doświadczenia. To jest zasadniczy problem wszelkich skomplikowanych bibliotek, które próbują wszystko rzekomo ułatwiać. Jak coś działa to super, ale jak nie działa, to nie wiadomo bez stack-overflow jak sobie z tym poradzić. 

:-(

**Comment by PatrykZaniewski** [comment]
Z tym min. 3-4 to dobrze Pan trafił bo ja spędziłem już 7 i różne emocje i słowa mi przy tym towarzyszyły 😃. 

Spróbuję do tego podejść tak jak Pan sugeruje, dziękuję.

**Comment by szmurlor** [comment]
Jeszcze jedna drobna uwaga: zazwyczaj, staram się rozwiązać tego typu problemy korzystając oczywiście z Internetu. Jednak, jeżeli po 1 godzinie ślęczenia i tzw. 'grzebaniu palcem w piasku' nie udaje mi się, to przełączam się w tryb deterministyczny - czyli w żmudne wyizolowanie miejsca występowania problemu.

Ze żmudnym podejściem, izolacyjnym mam pewną gwarancję, że w końcu uda i się. Szukanie w Internecie dłużej niż godzina to taka loteria - hazardzik trochę. Albo się uda i wtedy szybko mam rozwiązany problem, albo nie. 

Przy okazji żmudnego ślęczenia zazwyczaj człowiek przy okazji dużo się o frameworku dowiaduje - więc podwójna korzyść.

**Comment by PatrykZaniewski** [comment]
DZIAŁAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 🔥 🔥 🔥 !!!

Generalnie, problem okazał się mega prosty i nawet nie dotyczył Springa. Po prostu jak w postgresie jest typ character(n) i mamy zmienną o długości m to do tej zmiennej zawsze dokleja n-m białych znaków. Nie wiedziałem o tym, nie sprawdziłem długości stringa i taki jest efekt, że czas stracony :-(.
